version: '3.4'

services:
  dolarbot:
    container_name: dolarbot
    image: dolarbot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - dolarbot-data:/app/data
    env_file:
      - .env

volumes:
  dolarbot-data:
